"""
Diccionario de términos de DCSS para español (España).
Controla qué se traduce automáticamente y cómo.

Categorías:
- NO_TRANSLATE: términos que NO deben traducirse (nombres propios, dioses, únicos)
- FORCED_TERMS: traducciones forzadas EN->ES
- POST_PROCESS: correcciones posteriores a la traducción automática
"""

NO_TRANSLATE = {
    # === Dioses (nombres propios, no se traducen) ===
    "Ashenzari",
    "Beogh",
    "Cheibriados",
    "Dithmenos",
    "Fedhas",
    "Gozag",
    "Hepliaklqana",
    "Ignis",
    "Jiyva",
    "Kikubaaqudgha",
    "Lugonu",
    "Makhleb",
    "Nemelex Xobeh",
    "Okawaru",
    "Qazlal",
    "Ru",
    "Sif Muna",
    "Trog",
    "Uskayaw",
    "Vehumet",
    "Wu Jian",
    "Xom",
    "Yredelemnul",
    "Zin",
    "the Shining One",
    "The Shining One",
    "Shining One",
    "the Shining One",
    "the Serpent of Hell",
    "the Lernaean hydra",
    "the Royal Jelly",
    "the Enchantress",
    "the ghost of",
    "the pandemonium lord",
    # === Dioses: apodos/forma alternativa ===
    "Makhleb the Destroyer",
    "Sif Muna the Sage",
    "Okawaru the Warrior",
    "Trog the Wrathful",
    "Xom the Random",
    "Zin the Lawgiver",
    "Fedhas Madash",
    "Nemelex",
    # === Monstruos únicos (no traducir) ===
    "Aizul",
    "Asmodeus",
    "Antaeus",
    "Bai Suzhen",
    "Boris",
    "Cerebov",
    "Dissolution",
    "Donald",
    "Duvessa",
    "Ereshkigal",
    "Erolcha",
    "Frances",
    "Frederick",
    "Gastronok",
    "Gloorx Vloq",
    "Grum",
    "Harold",
    "Ijyb",
    "Jory",
    "Jozef",
    "Kirke",
    "Lom Lobon",
    "Louise",
    "Mara",
    "Margery",
    "Maud",
    "Mennas",
    "Meninges",
    "Mlioglotl",
    "Mnoleg",
    "Murray",
    "Nellie",
    "Nergalle",
    "Nikola",
    "Nissros",
    "Norris",
    "Pandemonium lord",
    "Pargi",
    "Polyphemus",
    "Prince Ribbit",
    "Psyche",
    "Purgy",
    "Roxanne",
    "Rupert",
    "Saint Roka",
    "Salmonella",
    "Saturn",
    "Sigmund",
    "Snorg",
    "Sojobo",
    "Tiamat",
    "Urug",
    "Vashnia",
    "Wiglaf",
    "Xtahua",
    "the Lernaean hydra",
    "the Serpent of Hell",
    "the Enchantress",
    "the Royal Jelly",
    "the ghost of",
    "the pandemonium lord",
    # === Nombres de ramas/zonas ===
    "the Abyss",
    "Abyss",
    "the Realm of Zot",
    "Zot",
    "the Orb",
    "Orb of Zot",
    "the Orb of Zot",
    "the Dungeon",
    "the Hells",
    "the Vestibule of Hell",
    "Cocytus",
    "Dis",
    "Gehenna",
    "Tartarus",
    "the Lair",
    "the Shoals",
    "the Slime Pits",
    "the Snake Pit",
    "the Spider Nest",
    "the Swamp",
    "the Orcish Mines",
    "the Elven Halls",
    "the Crypt",
    "the Tomb",
    "the Vaults",
    "the Depths",
    "the Hell",
    "the Pan",
    "Pandemonium",
    "Bailey",
    "Bazaar",
    "Ice Cave",
    "Ossuary",
    "Sewer",
    "Volcano",
    "Wizard Lab",
    "Ziggurat",
    "Desolation of Salt",
    "Gauntlet",
    "Trove",
    # === Lugares/objetos especiales ===
    "Zot",
    "the Orb",
    "the Orb of Zot",
    "the Crystal Ball of Energy",
    "the Horn of Geryon",
    "the Lamp of Fire",
    "the Box of Beasts",
    "the Silver Moonrock",
    "the Sublimation of Blood",
    "the Sceptre of Torment",
    "the Disc of Storms",
    "the Phantom Mirror",
    "the Elemental Staff",
    "the Staff of the Planes",
    "the Staff of Summoning",
    "the Staff of Wucad Mu",
    "the Staff of Olgreb",
    "the Tome of the Dragon",
    "the Tome of the Beast",
    "the Tome of the Sky",
    "the Tome of Shadows",
    "the Tome of Storms",
    "the Tome of Zay",
    "the Tome of Battle",
    "the Tome of Death",
    "the Tome of the Earth",
    "the Tome of the Sun",
    "the Tome of the Moon",
    "the Tome of the Void",
    "the Tome of the Worm",
    "Wucad Mu",
    "Olgreb",
    "Geryon",
    # === Especies que no se traducen ===
    "Barachi",
    "Coglin",
    "Djinni",
    "Draconian",
    "Felid",
    "Formicid",
    "Gnoll",
    "Kobold",
    "Merfolk",
    "Naga",
    "Octopode",
    "Oni",
    "Poltergeist",
    "Spriggan",
    "Tengu",
    "Tiefling",
    "Demonspawn",
    # === Backgrounds que no se traducen (nombres propios) ===
    "Berserker",
    "Hexslinger",
    "Shapeshifter",
    "Forgewright",
    "Delver",
    "Reaver",
    # === Gemas y armas especiales ===
    "Fedhas",
    "the Shining One",
    # === Tags de estado especiales ===
    "Fly",
    "Invis",
    "Tele",
    "Regen",
    "Berserk",
    "Pois",
    "Conf",
    "Contam",
    "Drain",
    "Slimify",
    "Rot",
    "Corr",
    "Petrify",
    "Sleep",
    "Paralysis",
    "Slow",
    "Haste",
    "Might",
    "Brill",
    "Agi",
    "Will",
    "Clarity",
    "RMsl",
    "RMut",
    "RCorr",
    "RElec",
    "RFire",
    "RCold",
    "RPoison",
    "RNeg",
    "Sticky Flame",
    "Sap Magic",
    "Still Winds",
    "Dimension Anchor",
    "Enchantress",
    "Portals",
    "battlelust",
    "inspiration",
    "duelist",
    "passwall",
    "Phase Shift",
    "Screaming",
    "Finesse",
    "Lunge",
    "Serpent's Lash",
    "Whirlwind",
    "blink",
    "landing",
    "cancelling",
    "warning",
    "flight",
}

FORCED_TERMS = {
    # =============================================
    # TIPOS DE DAÑO Y ELEMENTOS
    # =============================================
    "fire": "fuego",
    "fire damage": "daño de fuego",
    "cold": "frío",
    "cold damage": "daño de frío",
    "ice": "hielo",
    "ice damage": "daño de hielo",
    "electricity": "electricidad",
    "electrical": "eléctrico",
    "electric": "eléctrico",
    "lightning": "relámpago",
    "lightning damage": "daño de relámpago",
    "poison": "veneno",
    "poison damage": "daño de veneno",
    "poisonous": "venenoso",
    "poisoned": "envenenado",
    "poisoning": "envenenamiento",
    "acid": "ácido",
    "acid damage": "daño ácido",
    "corrosive": "corrosivo",
    "corrosion": "corrosión",
    "negative energy": "energía negativa",
    "negative energy damage": "daño de energía negativa",
    "draining": "drenante",
    "drain": "drenar",
    "steam": "vapor",
    "water": "agua",
    "earth": "tierra",
    "air": "aire",
    "magic": "magia",
    "magical": "mágico",
    "elemental": "elemental",
    "physical": "físico",
    "physical damage": "daño físico",
    "damage": "daño",
    "armour": "armadura",
    "armor": "armadura",
    # =============================================
    # ESTADÍSTICAS Y ATRIBUTOS
    # =============================================
    "health": "salud",
    "HP": "PV",
    "hit points": "puntos de vida",
    "magic": "magia",
    "MP": "PM",
    "magic points": "puntos de magia",
    "mana": "maná",
    "strength": "fuerza",
    "intelligence": "inteligencia",
    "dexterity": "destreza",
    "armour class": "clase de armadura",
    "AC": "CA",
    "evasion": "evasión",
    "EV": "EV",
    "evasion rating": "evasión",
    "shield": "escudo",
    "SH": "SH",
    "shield rating": "escudo",
    "willpower": "voluntad",
    "Will": "Voluntad",
    "will": "voluntad",
    "stealth": "sigilo",
    "speed": "velocidad",
    "accuracy": "precisión",
    "defence": "defensa",
    "defense": "defensa",
    "resistance": "resistencia",
    "resistant": "resistente",
    "immunity": "inmunidad",
    "immune": "inmune",
    "vulnerable": "vulnerable",
    "vulnerability": "vulnerabilidad",
    "heal": "curar",
    "healing": "curación",
    "regeneration": "regeneración",
    "regenerate": "regenerar",
    "duration": "duración",
    "range": "alcance",
    "radius": "radio",
    "power": "poder",
    "level": "nivel",
    "experience": "experiencia",
    "XP": "XP",
    "skill": "habilidad",
    "skills": "habilidades",
    "talent": "talento",
    "ability": "habilidad",
    "abilities": "habilidades",
    "effect": "efecto",
    "effects": "efectos",
    "chance": "probabilidad",
    "probability": "probabilidad",
    "weight": "peso",
    # =============================================
    # EQUIPAMIENTO Y OBJETOS
    # =============================================
    "weapon": "arma",
    "weapons": "armas",
    "armour": "armadura",
    "armor": "armadura",
    "shield": "escudo",
    "helmet": "casco",
    "helm": "casco",
    "hat": "sombrero",
    "cloak": "capa",
    "gloves": "guantes",
    "gauntlets": "guanteletes",
    "boots": "botas",
    "ring": "anillo",
    "amulet": "amuleto",
    "scroll": "pergamino",
    "scrolls": "pergaminos",
    "potion": "poción",
    "potions": "pociones",
    "wand": "varita",
    "wands": "varitas",
    "staff": "bastón",
    "staves": "bastones",
    "spellbook": "libro de hechizos",
    "spellbooks": "libros de hechizos",
    "book": "libro",
    "manual": "manual",
    "tome": "tomo",
    "jewelry": "joyas",
    "jewellery": "joyas",
    "gem": "gema",
    "gems": "gemas",
    "food": "comida",
    "ration": "ración",
    "meat": "carne",
    "bread": "pan",
    "fruit": "fruta",
    "pizza": "pizza",
    "ammunition": "munición",
    "ammo": "munición",
    "arrow": "flecha",
    "arrows": "flechas",
    "bolt": "virote",
    "bolts": "virotes",
    "quiver": "carcaj",
    "throwing": "arrojadizo",
    "missile": "proyectil",
    "missiles": "proyectiles",
    "blade": "hoja",
    "dagger": "daga",
    "sword": "espada",
    "long sword": "espada larga",
    "short sword": "espada corta",
    "great sword": "espada grande",
    "scimitar": "cimitarra",
    "falchion": "alfanje",
    "rapier": "estoque",
    "axe": "hacha",
    "battleaxe": "hacha de batalla",
    "broad axe": "hacha ancha",
    "great axe": "gran hacha",
    "hand axe": "hacha de mano",
    "mace": "maza",
    "club": "porra",
    "flail": "mayal",
    "morningstar": "estrella del alba",
    "war axe": "hacha de guerra",
    "spear": "lanza",
    "trident": "tridente",
    "halberd": "alabarda",
    "glaive": "guja",
    "scythe": "guadaña",
    "whip": "látigo",
    "demon whip": "látigo demoníaco",
    "bow": "arco",
    "longbow": "arco largo",
    "shortbow": "arco corto",
    "crossbow": "ballesta",
    "arbalest": "arbalesta",
    "hand crossbow": "ballesta de mano",
    "sling": "honda",
    "staff": "bastón",
    "quarterstaff": "bastón largo",
    "launcher": "arma de proyectiles",
    "body armour": "armadura corporal",
    "plate armour": "armadura de placas",
    "chain mail": "cota de malla",
    "scale mail": "armadura de escamas",
    "ring mail": "cota de anillas",
    "leather armour": "armadura de cuero",
    "robe": "túnica",
    "animal skin": "piel de animal",
    "troll leather": "cuero de trol",
    "dragon armour": "armadura de dragón",
    "fire dragon armour": "armadura de dragón de fuego",
    "ice dragon armour": "armadura de dragón de hielo",
    "pearl dragon armour": "armadura de dragón de perla",
    "golden dragon armour": "armadura de dragón dorado",
    "shadow dragon armour": "armadura de dragón de las sombras",
    "storm dragon armour": "armadura de dragón de tormenta",
    "swamp dragon armour": "armadura de dragón de ciénaga",
    "quicksilver dragon armour": "armadura de dragón de azogue",
    "buckler": "broquel",
    "shield": "escudo",
    "large shield": "escudo grande",
    # =============================================
    # CALIDADES Y PROPIEDADES DE OBJETOS
    # =============================================
    "uncursed": "sin maldecir",
    "cursed": "maldecido",
    "blessed": "bendecido",
    "enchanted": "encantado",
    "magical": "mágico",
    "glowing": "brillante",
    "shiny": "reluciente",
    "runed": "grabado",
    "emblazoned": "embanderado",
    "engraved": "grabado",
    "ancient": "antiguo",
    "artefact": "artefacto",
    "artifact": "artefacto",
    "randart": "artefacto aleatorio",
    "brand": "atributo",
    "ego": "atributo",
    "worthless": "sin valor",
    "useless": "inútil",
    "crude": "basto",
    "fine": "fino",
    "exceptional": "excepcional",
    "masterwork": "magistral",
    # =============================================
    # ATRIBUTOS DE ARMAS (EGOS/BRANDS)
    # =============================================
    "flaming": "llameante",
    "freezing": "congelante",
    "electrocution": "electrocución",
    "pain": "dolor",
    "holy wrath": "ira divina",
    "distortion": "distorsión",
    "vampirism": "vampirismo",
    "draining": "drenante",
    "chaos": "caos",
    "speed": "celeridad",
    "vorpal": "vórtice",
    "venom": "veneno",
    "protecting": "protector",
    "antimagic": "antimagia",
    "heavy": "pesado",
    "penetration": "penetración",
    "returning": "retornante",
    "reaching": "alcance",
    "spirit shield": "escudo espiritual",
    "stealth": "sigilo",
    "stabbing": "apuñalar",
    "invisibility": "invisibilidad",
    "silver": "argéntea",
    "willpower": "voluntad",
    "protection": "protección",
    "clarity": "claridad",
    "see invisible": "ver lo invisible",
    "rPois": "rVen",
    "rF": "rFue",
    "rC": "rFr",
    "rElec": "rElec",
    "rNeg": "rNeg",
    "rCorr": "rCorr",
    "rMut": "rMut",
    "slaying": "exterminio",
    "curse": "maldición",
    "cursed": "maldecido",
    "enchantment": "encantamiento",
    "recharge": "recargar",
    "identification": "identificación",
    "evoke": "evocar",
    "evokable": "evocable",
    "evocations": "evocación",
    "inscrutable": "inscrutable",
    "unidentified": "sin identificar",
    "identified": "identificado",
    # =============================================
    # ESPECIES (TRADUCCIONES)
    # =============================================
    "Barachi": "Barachi",
    "Coglin": "Coglin",
    "Deep Elf": "Elfo Profundo",
    "Deep Elves": "Elfos Profundos",
    "Demigod": "Semidiós",
    "Demigods": "Semidioses",
    "Demonspawn": "Semidemonio",
    "Djinni": "Genio",
    "Djinn": "Genios",
    "Draconian": "Draconiano",
    "Draconians": "Draconianos",
    "Felid": "Félido",
    "Felids": "Félidos",
    "Formicid": "Formícido",
    "Formicids": "Formícidos",
    "Gale Centaur": "Centauro Galerna",
    "Gale Centaurs": "Centauros Galerna",
    "Gargoyle": "Gárgola",
    "Gargoyles": "Gárgolas",
    "Gnoll": "Gnoll",
    "Gnolls": "Gnolls",
    "Halfling": "Mediano",
    "Halflings": "Medianos",
    "Hill Orc": "Orco de las Colinas",
    "Hill Orcs": "Orcos de las Colinas",
    "Human": "Humano",
    "Humans": "Humanos",
    "Kobold": "Kobold",
    "Kobolds": "Kobolds",
    "Merfolk": "Tritón",
    "Minotaur": "Minotauro",
    "Minotaurs": "Minotauros",
    "Mountain Dwarf": "Enano de Montaña",
    "Mountain Dwarves": "Enanos de Montaña",
    "Mummy": "Momia",
    "Mummies": "Momias",
    "Naga": "Naga",
    "Nagas": "Nagas",
    "Octopode": "Octópodo",
    "Octopodes": "Octópodos",
    "Oni": "Oni",
    "Poltergeist": "Poltergeist",
    "Revenant": "Revenant",
    "Revenants": "Revenants",
    "Spriggan": "Spriggan",
    "Spriggans": "Spriggans",
    "Tengu": "Tengu",
    "Tiefling": "Tiefling",
    "Tieflings": "Tieflings",
    "Troll": "Trol",
    "Trolls": "Troles",
    "Vampire": "Vampiro",
    "Vampires": "Vampiros",
    "Vine Stalker": "Acechador de Enredaderas",
    "Vine Stalkers": "Acechadores de Enredaderas",
    "Deep Dwarf": "Enano Profundo",
    "Deep Dwarves": "Enanos Profundos",
    "Deep Elf": "Elfo Profundo",
    "Deep Elves": "Elfos Profundos",
    "Demigod": "Semidiós",
    "Demigods": "Semidioses",
    "Demonspawn": "Semidemonio",
    "Centaur": "Centauro",
    "Centaurs": "Centauros",
    "Gargoyle": "Gárgola",
    # =============================================
    # BACKGROUNDS (CLASES)
    # =============================================
    "Air Elementalist": "Elementalista de Aire",
    "Alchemist": "Alquimista",
    "Alchemists": "Alquimistas",
    "Arcane Marksman": "Tirador Arcano",
    "Artificer": "Artificiero",
    "Artificers": "Artificieros",
    "Assassin": "Asesino",
    "Berserker": "Berserker",
    "Brigand": "Bandolero",
    "Chaos Knight": "Caballero del Caos",
    "Chaos Knights": "Caballeros del Caos",
    "Cinder Acolyte": "Acólito de Ascuas",
    "Conjurer": "Conjurador",
    "Conjurers": "Conjuradores",
    "Crusader": "Cruzado",
    "Death Knight": "Caballero de la Muerte",
    "Delver": "Explorador",
    "Devotee of Nemelex": "Devoto de Nemelex",
    "Earth Elementalist": "Elementalista de Tierra",
    "Enchanter": "Encantador",
    "Enchanters": "Encantadores",
    "Fighter": "Guerrero",
    "Fighters": "Guerreros",
    "Fire Elementalist": "Elementalista de Fuego",
    "Forgewright": "Forjador",
    "Gladiator": "Gladiador",
    "Hedge Wizard": "Mago Rustico",
    "Hedge Wizards": "Magos Rusticos",
    "Hexslinger": "Tirador de Maldiciones",
    "Hunter": "Cazador",
    "Hunters": "Cazadores",
    "Ice Elementalist": "Elementalista de Hielo",
    "Jester": "Bufón",
    "Monk": "Monje",
    "Monks": "Monjes",
    "Necromancer": "Nigromante",
    "Necromancers": "Nigromantes",
    "Paladin": "Paladín",
    "Pickpocket": "Carterista",
    "Priest": "Sacerdote",
    "Reaver": "Saqueador",
    "Shapeshifter": "Cambiaformas",
    "Skald": "Escaldo",
    "Summoner": "Invocador",
    "Summoners": "Invocadores",
    "Wanderer": "Vagabundo",
    "Wanderers": "Vagabundos",
    "Warper": "Deformador",
    "Warpers": "Deformadores",
    "Warlock": "Brujo",
    "Wizard": "Mago",
    # =============================================
    # HECHIZOS (nombres comunes y palabras de conjuros)
    # =============================================
    "spell": "hechizo",
    "spells": "hechizos",
    "magic": "magia",
    "magical": "mágico",
    "conjuration": "conjuración",
    "conjure": "conjurar",
    "summon": "invocar",
    "summoning": "invocación",
    "summoned": "invocado",
    "translocation": "traslocación",
    "transmutation": "transmutación",
    "transmute": "transmutar",
    "hex": "maleficio",
    "hexes": "maleficios",
    "necromancy": "nigromancia",
    "necromantic": "nigromántico",
    "enchantment": "encantamiento",
    "enchant": "encantar",
    "fire magic": "magia de fuego",
    "ice magic": "magia de hielo",
    "air magic": "magia de aire",
    "earth magic": "magia de tierra",
    "poison magic": "magia de veneno",
    "cast": "lanzar",
    "casting": "lanzamiento",
    "caster": "lanzador",
    "wizard": "mago",
    "mage": "mago",
    "magic": "magia",
    "magical": "mágico",
    "sorcerer": "hechicero",
    "sorcery": "hechicería",
    "spellpower": "poder de hechizo",
    "spell power": "poder de hechizo",
    "spell level": "nivel de hechizo",
    # =============================================
    # COMBATE Y ACCIONES
    # =============================================
    "attack": "atacar",
    "attacks": "ataques",
    "attacker": "atacante",
    "melee": "cuerpo a cuerpo",
    "ranged": "a distancia",
    "hit": "golpe",
    "hits": "golpea",
    "damage": "daño",
    "injure": "herir",
    "wound": "herida",
    "kill": "matar",
    "kills": "mata",
    "death": "muerte",
    "die": "morir",
    "destroy": "destruir",
    "destruction": "destrucción",
    "smite": "castigar",
    "bless": "bendecir",
    "blessing": "bendición",
    "curse": "maldición",
    "cursed": "maldecido",
    "protect": "proteger",
    "protection": "protección",
    "shield": "escudo",
    "block": "bloquear",
    "dodge": "esquivar",
    "evade": "evadir",
    "evasion": "evasión",
    "strike": "golpear",
    "strikes": "golpea",
    "slash": "cuchillada",
    "stab": "apuñalar",
    "stabbing": "apuñalamiento",
    "backstab": "apuñalar por la espalda",
    "critical hit": "golpe crítico",
    "throw": "lanzar",
    "fire": "disparar",
    "shoot": "disparar",
    "aim": "apuntar",
    "target": "objetivo",
    "targets": "objetivos",
    "enemy": "enemigo",
    "enemies": "enemigos",
    "foe": "enemigo",
    "foes": "enemigos",
    "friend": "amigo",
    "friendly": "amistoso",
    "ally": "aliado",
    "allies": "aliados",
    "monster": "monstruo",
    "monsters": "monstruos",
    "creature": "criatura",
    "creatures": "criaturas",
    "being": "ser",
    "beings": "seres",
    "victim": "víctima",
    "victims": "víctimas",
    "hostile": "hostil",
    "neutral": "neutral",
    "berserk": "berserk",
    "confused": "confundido",
    "confusion": "confusión",
    "paralysed": "paralizado",
    "paralysis": "parálisis",
    "petrified": "petrificado",
    "petrification": "petrificación",
    "sleeping": "dormido",
    "asleep": "dormido",
    "slow": "lento",
    "slowed": "ralentizado",
    "haste": "celeridad",
    "hasted": "acelerado",
    "blink": "parpadeo",
    "teleport": "teletransporte",
    "teleportation": "teletransporte",
    "portal": "portal",
    # =============================================
    # HABILIDADES (SKILLS)
    # =============================================
    "Fighting": "Pelea",
    "Dodging": "Esquivar",
    "Stealth": "Sigilo",
    "Throwing": "Armas arrojadizas",
    "Unarmed Combat": "Combate sin armas",
    "Long Blades": "Hojas largas",
    "Short Blades": "Hojas cortas",
    "Axes": "Hachas",
    "Maces & Flails": "Mazas y mayales",
    "Polearms": "Armas de asta",
    "Staves": "Bastones",
    "Slings": "Hondas",
    "Bows": "Arcos",
    "Crossbows": "Ballestas",
    "Armour": "Armadura",
    "Shields": "Escudos",
    "Spellcasting": "Lanzamiento de hechizos",
    "Conjurations": "Conjuraciones",
    "Hexes": "Maleficios",
    "Summonings": "Invocaciones",
    "Necromancy": "Nigromancia",
    "Translocations": "Traslocaciones",
    "Transmutations": "Transmutaciones",
    "Fire Magic": "Magia de fuego",
    "Ice Magic": "Magia de hielo",
    "Air Magic": "Magia de aire",
    "Earth Magic": "Magia de tierra",
    "Poison Magic": "Magia de veneno",
    "Invocation": "Invocación divina",
    "Evocations": "Evocación",
    "Shapeshifting": "Cambiaformas",
    "skill": "habilidad",
    "skills": "habilidades",
    "skill level": "nivel de habilidad",
    # =============================================
    # OBJETOS COMUNES - NOMBRES
    # =============================================
    "potion of curing": "poción de curación",
    "potion of heal wounds": "poción de curación de heridas",
    "potion of might": "poción de poderío",
    "potion of berserk rage": "poción de furia berserker",
    "potion of agility": "poción de agilidad",
    "potion of brilliance": "poción de brillantez",
    "potion of haste": "poción de celeridad",
    "potion of invisibility": "poción de invisibilidad",
    "potion of flight": "poción de vuelo",
    "potion of resistance": "poción de resistencia",
    "potion of magic": "poción de magia",
    "potion of restore abilities": "poción de restauración de atributos",
    "potion of cure mutation": "poción de cura de mutación",
    "potion of mutation": "poción de mutación",
    "potion of beneficial mutation": "poción de mutación beneficiosa",
    "potion of experience": "poción de experiencia",
    "potion of attraction": "poción de atracción",
    "potion of degeneration": "poción de degeneración",
    "potion of lignification": "poción de lignificación",
    "scroll of identify": "pergamino de identificación",
    "scroll of teleportation": "pergamino de teletransporte",
    "scroll of blinking": "pergamino de parpadeo",
    "scroll of fear": "pergamino de miedo",
    "scroll of noise": "pergamino de ruido",
    "scroll of fog": "pergamino de niebla",
    "scroll of magic mapping": "pergamino de cartografía mágica",
    "scroll of enchant armour": "pergamino de encantar armadura",
    "scroll of enchant weapon": "pergamino de encantar arma",
    "scroll of branding": "pergamino de atributo",
    "scroll of recharging": "pergamino de recarga",
    "scroll of acquirement": "pergamino de adquisición",
    "scroll of amnesia": "pergamino de amnesia",
    "scroll of torment": "pergamino de tormento",
    "scroll of summoning": "pergamino de invocación",
    "scroll of immolation": "pergamino de inmolación",
    "scroll of silence": "pergamino de silencio",
    "scroll of vulnerability": "pergamino de vulnerabilidad",
    "scroll of holy word": "pergamino de palabra sagrada",
    "scroll of butterflies": "pergamino de mariposas",
    "wand of flame": "varita de llama",
    "wand of iceblast": "varita de explosión de hielo",
    "wand of polymorph": "varita de polimorfia",
    "wand of charming": "varita de encantamiento",
    "wand of digging": "varita de excavación",
    "wand of random effects": "varita de efectos aleatorios",
    "wand of paralysis": "varita de parálisis",
    "wand of clouds": "varita de nubes",
    "wand of scattershot": "varita de ráfaga",
    "wand of acid": "varita de ácido",
    "wand of light": "varita de luz",
    "wand of mindsight": "varita de vision mental",
    "wand of hasting": "varita de celeridad",
    "wand of heal wounds": "varita de curación de heridas",
    "wand of invisibility": "varita de invisibilidad",
    "wand of magic darts": "varita de dardos mágicos",
    "wand of quake": "varita de terremoto",
    "wand of roots": "varita de raíces",
    "wand of slowing": "varita de lentitud",
    # =============================================
    # ESTADOS Y EFECTOS
    # =============================================
    "status": "estado",
    "effect": "efecto",
    "effects": "efectos",
    "buff": "beneficio",
    "debuff": "perjuicio",
    "aura": "aura",
    "cloud": "nube",
    "clouds": "nubes",
    "flame": "llama",
    "flames": "llamas",
    "fire": "fuego",
    "smoke": "humo",
    "steam": "vapor",
    "poison gas": "gas venenoso",
    "noxious fumes": "gases nocivos",
    "deep water": "agua profunda",
    "shallow water": "agua poco profunda",
    "lava": "lava",
    "mud": "barro",
    "slimy": "limoso",
    "sticky": "pegajoso",
    "congealed": "coagulado",
    "frozen": "congelado",
    "burning": "ardiendo",
    "on fire": "en llamas",
    "corroding": "corroyendo",
    "sticky flame": "llama pegajosa",
    "sap magic": "drenar magia",
    "silence": "silencio",
    "amnesia": "amnesia",
    "invisible": "invisible",
    "invisibility": "invisibilidad",
    "see invisible": "ver lo invisible",
    "hidden": "oculto",
    "revealed": "revelado",
    "detected": "detectado",
    "detection": "detección",
    "sensing": "detección",
    "aware": "consciente",
    "unaware": "inconsciente",
    "alert": "alerta",
    "sleeping": "durmiendo",
    "wandering": "deambulando",
    "patrolling": "patrullando",
    "following": "siguiendo",
    # =============================================
    # TÉRMINOS GENERALES DEL JUEGO
    # =============================================
    "dungeon": "calabozo",
    "level": "nivel",
    "floor": "planta",
    "branch": "rama",
    "stair": "escalera",
    "stairs": "escaleras",
    "trap": "trampa",
    "traps": "trampas",
    "door": "puerta",
    "doors": "puertas",
    "gate": "compuerta",
    "chest": "cofre",
    "chests": "cofres",
    "altar": "altar",
    "altars": "altares",
    "fountain": "fuente",
    "fountains": "fuentes",
    "tomb": "tumba",
    "grave": "tumba",
    "vault": "bóveda",
    "shop": "tienda",
    "shops": "tiendas",
    "merchant": "mercader",
    "temple": "templo",
    "shrine": "santuario",
    "portal": "portal",
    "portals": "portales",
    "passage": "pasaje",
    "corridor": "corredor",
    "room": "habitación",
    "chamber": "cámara",
    "hall": "salón",
    "cavern": "caverna",
    "cave": "cueva",
    "tunnel": "túnel",
    "lair": "guarida",
    "nest": "nido",
    "sanctuary": "santuario",
    "arena": "arena",
    "colosseum": "coliseo",
    "laboratory": "laboratorio",
    "tower": "torre",
    "castle": "castillo",
    "fortress": "fortaleza",
    "ruin": "ruina",
    "ruins": "ruinas",
    # =============================================
    # ACCIONES E INTERFAZ
    # =============================================
    "you": "tú",
    "your": "tu",
    "you are": "estás",
    "you have": "tienes",
    "you can": "puedes",
    "you must": "debes",
    "you cannot": "no puedes",
    "you may": "puedes",
    "you will": "podrás",
    "you would": "podrías",
    "you feel": "sientes",
    "you see": "ves",
    "you hear": "oyes",
    "you smell": "hueles",
    "Press": "Pulsa",
    "press": "pulsa",
    "key": "tecla",
    "menu": "menú",
    "option": "opción",
    "options": "opciones",
    "setting": "ajuste",
    "settings": "ajustes",
    "command": "comando",
    "commands": "comandos",
    "action": "acción",
    "actions": "acciones",
    "cancel": "cancelar",
    "confirm": "confirmar",
    "accept": "aceptar",
    "reject": "rechazar",
    "choose": "elegir",
    "select": "seleccionar",
    "pick": "escoger",
    "yes": "sí",
    "no": "no",
    "on": "activado",
    "off": "desactivado",
    "enable": "activar",
    "disable": "desactivar",
    "auto": "automático",
    "manual": "manual",
    # =============================================
    # DIOSES: TÉRMINOS ASOCIADOS
    # =============================================
    "piety": "piedad",
    "penance": "penitencia",
    "prayer": "oración",
    "pray": "rezar",
    "worship": "adorar",
    "worshipper": "adorador",
    "devotion": "devoción",
    "devout": "devoto",
    "follower": "seguidor",
    "followers": "seguidores",
    "altar": "altar",
    "sacrifice": "sacrificio",
    "sacrifice": "sacrificar",
    "offering": "ofrenda",
    "offering": "ofrecer",
    "blessing": "bendición",
    "bless": "bendecir",
    "curse": "maldición",
    "cursed": "maldecido",
    "wrath": "ira",
    "fury": "furía",
    "anger": "enfado",
    "favour": "favor",
    "boon": "don",
    "gift": "regalo",
    "reward": "recompensa",
    "punish": "castigar",
    "punishment": "castigo",
    "retribution": "retribución",
    "vengeance": "venganza",
    # =============================================
    # CRIATURAS COMUNES
    # =============================================
    "goblin": "trasgo",
    "goblins": "trasgos",
    "orc": "orco",
    "orcs": "orcos",
    "hobgoblin": "trasgo mayor",
    "hobgoblins": "trasgos mayores",
    "ogre": "ogro",
    "ogres": "ogros",
    "troll": "trol",
    "trolls": "troles",
    "dragon": "dragón",
    "dragons": "dragones",
    "drake": "draco",
    "drakes": "dracos",
    "wyrm": "dragón",
    "worm": "gusano",
    "worms": "gusanos",
    "snake": "serpiente",
    "snakes": "serpientes",
    "spider": "araña",
    "spiders": "arañas",
    "scorpion": "escorpión",
    "scorpions": "escorpiones",
    "centipede": "ciempiés",
    "centipedes": "ciempiés",
    "bee": "abeja",
    "bees": "abejas",
    "wasp": "avispa",
    "wasps": "avispas",
    "ant": "hormiga",
    "ants": "hormigas",
    "beetle": "escarabajo",
    "beetles": "escarabajos",
    "rat": "rata",
    "rats": "ratas",
    "bat": "murciélago",
    "bats": "murciélagos",
    "wolf": "lobo",
    "wolves": "lobos",
    "hound": "sabueso",
    "hell hound": "sabueso infernal",
    "hell beast": "bestia infernal",
    "bear": "oso",
    "bears": "osos",
    "boar": "jabalí",
    "boars": "jabalíes",
    "hog": "cerdo",
    "elephant": "elefante",
    "mammoth": "mamut",
    "yak": "yak",
    "sheep": "oveja",
    "goat": "cabra",
    "cow": "vaca",
    "horse": "caballo",
    "unicorn": "unicornio",
    "deer": "ciervo",
    "rabbit": "conejo",
    "squirrel": "ardilla",
    "fox": "zorro",
    "hawk": "halcón",
    "raven": "cuervo",
    "crow": "corneja",
    "vulture": "buitre",
    "eagle": "águila",
    "owl": "búho",
    "lizard": "lagarto",
    "newt": "tritón",
    "frog": "rana",
    "toad": "sapo",
    "turtle": "tortuga",
    "crab": "cangrejo",
    "lobster": "langosta",
    "shark": "tiburón",
    "fish": "pez",
    "eel": "anguila",
    "squid": "calamar",
    "jelly": "gelatina",
    "slime": "limo",
    "ooze": "limo",
    "blob": "masa amorfa",
    "eye": "ojo",
    "eyes": "ojos",
    "floating eye": "ojo flotante",
    "giant eyeball": "ojo gigante",
    "golem": "gólem",
    "golems": "gólems",
    "statue": "estatua",
    "spectral": "espectral",
    "spirit": "espíritu",
    "ghost": "fantasma",
    "phantom": "fantasma",
    "wraith": "espectro",
    "shade": "sombra",
    "shadow": "sombra",
    "skeleton": "esqueleto",
    "skeletons": "esqueletos",
    "zombie": "zombi",
    "zombies": "zombis",
    "necromancer": "nigromante",
    "lich": "liche",
    "liches": "liches",
    "vampire": "vampiro",
    "vampires": "vampiros",
    "demon": "demonio",
    "demons": "demonios",
    "imp": "diablillo",
    "imps": "diablillos",
    "fiend": "diablo",
    "devil": "diablo",
    "abomination": "abominación",
    "ugly thing": "cosa horrible",
    "very ugly thing": "cosa horrorosa",
    "elf": "elfo",
    "elves": "elfos",
    "deep elf": "elfo profundo",
    "deep elves": "elfos profundos",
    "high elf": "elfo alto",
    "dwarf": "enano",
    "dwarves": "enanos",
    "deep dwarf": "enano profundo",
    "deep dwarves": "enanos profundos",
    "hill dwarf": "enano de las colinas",
    "spriggan": "spriggan",
    "spriggans": "spriggans",
    "human": "humano",
    "humans": "humanos",
    "naga": "naga",
    "nagas": "nagas",
    "tengu": "tengu",
    "tengu": "tengus",
    "merfolk": "tritón",
    "mermaid": "sirena",
    "merman": "tritón",
    "minotaur": "minotauro",
    "minotaurs": "minotauros",
    "centaur": "centauro",
    "centaurs": "centauros",
    "satyr": "sátiro",
    "satyrs": "sátiros",
    "faun": "fauno",
    "nymph": "ninfa",
    "moth": "polilla",
    "butterfly": "mariposa",
    "butterflies": "mariposas",
    "boggart": "bogart",
    "will-o'-the-wisp": "fuego fatuo",
    "wisp": "fatuo",
    "elemental": "elemental",
    "earth elemental": "elemental de tierra",
    "fire elemental": "elemental de fuego",
    "ice elemental": "elemental de hielo",
    "air elemental": "elemental de aire",
    "water elemental": "elemental de agua",
    "mithril": "mitril",
    "adamant": "adamante",
    "adamantine": "adamantita",
    "balsa": "balsa",
    "bone": "hueso",
    "crystal": "cristal",
    "glass": "vidrio",
    "gold": "oro",
    "iron": "hierro",
    "lead": "plomo",
    "leather": "cuero",
    "metal": "metal",
    "paper": "papel",
    "platinum": "platino",
    "rubber": "caucho",
    "silver": "plata",
    "steel": "acero",
    "stone": "piedra",
    "wool": "lana",
    "wood": "madera",
    "zongonite": "zongonita",
    # =============================================
    # PALABRAS DE COMBATE Y ACCIÓN
    # =============================================
    "burns": "quema",
    "burns": "ardiente",
    "freezes": "congela",
    "freezing": "congelante",
    "strikes": "golpea",
    "striking": "golpeando",
    "hits": "golpea",
    "hitting": "golpeando",
    "slashes": "cuchilla",
    "cuts": "corta",
    "pierces": "perfora",
    "piercing": "perforante",
    "blasts": "explota",
    "blasting": "explosivo",
    "explodes": "explota",
    "explosion": "explosión",
    "explosive": "explosivo",
    "shatters": "destroza",
    "crushing": "aplastante",
    "crushes": "aplasta",
    "smashing": "impactante",
    "smashes": "impacta",
    "wounds": "hiere",
    "wounding": "hiriente",
    "mauls": "magulla",
    "mauling": "magullante",
    "bites": "muerde",
    "biting": "mordedor",
    "stings": "pica",
    "stinging": "picante",
    "touches": "toca",
    "touching": "tocante",
    "grabs": "agarra",
    "grabbing": "agarrador",
    "holds": "sujeta",
    "holding": "sujetador",
    "engulfs": "engulle",
    "engulfing": "engullidor",
    "consumes": "consume",
    "consuming": "consumidor",
    "devours": "devora",
    "devouring": "devorador",
    "retreats": "retrocede",
    "retreating": "retrocediendo",
    "flees": "huye",
    "fleeing": "huyendo",
    "advances": "avanza",
    "advancing": "avanzando",
    "charges": "carga",
    "charging": "cargando",
    "dodges": "esquiva",
    "dodging": "esquivando",
    "blocks": "bloquea",
    "blocking": "bloqueando",
    "reflects": "refleja",
    "reflecting": "reflejando",
    "absorbs": "absorbe",
    "absorbing": "absorbiendo",
    "resists": "resiste",
    "resisting": "resistiendo",
    # =============================================
    # ALTARES Y DESCRIPCIONES DE ESCENARIOS
    # =============================================
    "altar": "altar",
    "glowing golden altar": "altar dorado y resplandeciente",
    "blossoming altar": "altar floreciente",
    "candlelit altar": "altar iluminado por velas",
    "corrupted altar": "altar corrompido",
    "burning altar": "altar ardiente",
    "deep blue altar": "altar azul profundo",
    "ecumenical altar": "altar ecuménico",
    "glistening altar": "altar reluciente",
    "glowing altar": "altar resplandeciente",
    "iron altar": "altar de hierro",
    "mossy altar": "altar musgoso",
    "shining altar": "altar brillante",
    "silvery altar": "altar plateado",
    "smoking altar": "altar humeante",
    "stone altar": "altar de piedra",
    "white marble altar": "altar de mármol blanco",
    "wicked altar": "altar malvado",
    # =============================================
    # MATERIALES Y SUSTANCIAS
    # =============================================
    "bronze": "bronce",
    "copper": "cobre",
    "steel": "acero",
    "iron": "hierro",
    "silver": "plata",
    "gold": "oro",
    "platinum": "platino",
    "mithril": "mitril",
    "crystal": "cristal",
    "glass": "vidrio",
    "bone": "hueso",
    "ivory": "marfil",
    "stone": "piedra",
    "marble": "mármol",
    "granite": "granito",
    "obsidian": "obsidiana",
    "wooden": "madera",
    "oak": "roble",
    "ebony": "ébano",
    "yew": "tejo",
    "leather": "cuero",
    "hide": "cuero",
    "scale": "escama",
    "dragonhide": "cuero de dragón",
    "dragon skin": "piel de dragón",
    "silk": "seda",
    "cotton": "algodón",
    "linen": "lino",
    "wool": "lana",
    "felt": "fieltro",
    "cloth": "tela",
    "velvet": "terciopelo",
    # =============================================
    # GEMAS Y PIEDRAS PRECIOSAS
    # =============================================
    "ruby": "rubí",
    "sapphire": "zafiro",
    "emerald": "esmeralda",
    "diamond": "diamante",
    "amethyst": "amatista",
    "opal": "ópalo",
    "garnet": "granate",
    "topaz": "topacio",
    "jade": "jade",
    "pearl": "perla",
    "coral": "coral",
    "amber": "ámbar",
    "moonstone": "piedra de luna",
    "turquoise": "turquesa",
    "lapis lazuli": "lapislázuli",
    "onyx": "ónix",
    "bloodstone": "hematites",
    # =============================================
    # PALABRAS PARA ESTADÍSTICAS
    # =============================================
    "moderate": "moderado",
    "heavy": "pesado",
    "light": "ligero",
    "weak": "débil",
    "strong": "fuerte",
    "powerful": "poderoso",
    "greater": "superior",
    "lesser": "inferior",
    "minor": "menor",
    "major": "mayor",
    "extreme": "extremo",
    "severe": "severo",
    "average": "medio",
    "normal": "normal",
    "maximum": "máximo",
    "minimum": "mínimo",
    "total": "total",
    "partial": "parcial",
    "complete": "completo",
    "increased": "aumentado",
    "reduced": "reducido",
    "additional": "adicional",
    "extra": "extra",
    "bonus": "bonificación",
    # =============================================
    # VERBOS COMUNES
    # =============================================
    "use": "usar",
    "uses": "usa",
    "used": "usado",
    "usable": "usable",
    "usable": "utilizable",
    "equip": "equipar",
    "equipped": "equipado",
    "unequip": "desequipar",
    "wield": "empuñar",
    "wielding": "empuñando",
    "wear": "vestir",
    "wearing": "vistiendo",
    "remove": "quitar",
    "drop": "soltar",
    "dropped": "soltado",
    "pick up": "recoger",
    "collect": "recoger",
    "collecting": "recogiendo",
    "carry": "llevar",
    "carrying": "llevando",
    "store": "almacenar",
    "storing": "almacenando",
}

# =============================================
# POST-PROCESO: correcciones tras traducción automática
# =============================================
# Estas son tuplas (patrón_re, reemplazo) aplicadas en orden
# después de que LibreTranslate devuelva el texto traducido.
POST_PROCESS = [
    # Correcciones de género/número que LT suele fallar
    (r"\bel\b", "el"),  # "el" should always be lowercase in middle of text
    (r"\bla\b", "la"),  # "la" should always be lowercase
    (r"\blos\b", "los"),
    (r"\blas\b", "las"),
    # Artículos incorrectos con palabras femeninas
    (r"el armadura", "la armadura"),
    (r"el arma", "el arma"),  # correcto, arma es femenino pero usa "el"
    (r"el agua", "el agua"),  # correcto
    (r"el hacha", "el hacha"),  # correcto
    (r"el área", "el área"),  # correcto
    (r"un armadura", "una armadura"),
    (r"un arma", "un arma"),  # correcto
    (r"un hacha", "un hacha"),  # correcto
    (r"un área", "un área"),  # correcto
    # LT confunde "you" con "usted" en vez de "tú"
    (r"\bUsted\b", "Tú"),  # después de punto
    (r"\busted\b", "tú"),
    (r"\bUsted está\b", "Estás"),
    (r"\busted está\b", "estás"),
    (r"\bUsted tiene\b", "Tienes"),
    (r"\busted tiene\b", "tienes"),
    (r"\bUsted puede\b", "Puedes"),
    (r"\busted puede\b", "puedes"),
    # LT confunde "tú" con "vos" (voseo)
    (r"\bvos\b", "tú"),
    (r"\btenés\b", "tienes"),
    (r"\bsos\b", "eres"),
    # LT mete "de" donde no toca
    (r"el daño de fuego", "daño de fuego"),
    (r"el daño de frío", "daño de frío"),
    (r"el daño de veneno", "daño de veneno"),
    (r"el daño de", "daño de"),
    # LT suele poner "por" donde va "de" en atributos
    (r"resistencia por", "resistencia a"),
    (r"inmunidad por", "inmunidad a"),
    (r"resistente por", "resistente a"),
    (r"inmune por", "inmune a"),
    (r"vulnerable por", "vulnerable a"),
    (r"vulnerabilidad por", "vulnerabilidad a"),
    # LT confunde "armour" como "amor"
    (r"\bamor\b", "armadura"),
    # LT suele poner "Hechizo de X" como "Sortilegio de X" o "Embrujo"
    (r"\bsortilegio\b", "hechizo"),
    (r"\bembrujo\b", "hechizo"),
    (r"\bconjuro\b", "hechizo"),
    (r"\bencantamiento\b", "hechizo"),  # cuando se refiere a un spell no a un enchant
    (r"\bSortilegio\b", "Hechizo"),
    (r"\bEmbrujo\b", "Hechizo"),
    (r"\bConjuro\b", "Hechizo"),
    # LT suele poner "Monstruo" con mayúscula en medio de frase
    (r"un Monstruo", "un monstruo"),
    (r"el Monstruo", "el monstruo"),
    (r"los Monstruos", "los monstruos"),
    (r"la Monstruo", "el monstruo"),
    # LT: "dañar" vs "daño" (solo cuando es claramente sustantivo mal usado)
    (r"\bdañar a\b", "daño a"),
    # LT: "nivel" en vez de "nivel" -> lo dejamos, "nivel" is correct Spanish
    # Pero si pone "nivvel" o cualquier variante rara:
    (r"\bnivel\b", "nivel"),  # ensure correct
    (r"\bpointos\b", "puntos"),
    (r"\bpuntos de vida\b", "puntos de vida"),
    (r"\bpuntos de magia\b", "puntos de magia"),
    # Restaurar nombres de dioses que LT pueda castellanizar
    (r"\bTroya\b", "Trog"),  # LT might confuse Trog with Troy
    (r"\bZin\b", "Zin"),  # ensure Zin stays
    (r"\bXom\b", "Xom"),  # ensure Xom stays
    (r"\bRu\b", "Ru"),  # ensure Ru stays
    (r"\bAsquenazi\b", "Ashenzari"),  # LT might mangle
    (r"\bBog\b", "Beogh"),  # LT might mangle
    (r"\bMajleb\b", "Makhleb"),  # LT might mangle
    # Restaurar nombres de especies que LT castellaniza mal
    (r"\bFelidae\b", "Félido"),
    (r"\bFelinos\b", "Félidos"),
    (r"\bGárgola\b", "Gárgola"),  # ensure proper capital
    (r"\bSemidiós\b", "Semidiós"),
    (r"\bSemidemonio\b", "Semidemonio"),
    (r"\bFormícida\b", "Formícido"),
    (r"\bFormicidae\b", "Formícido"),
    (r"\bDraconiano\b", "Draconiano"),
    (r"\bGenio\b", "Genio"),
    (r"\bRevenant\b", "Revenant"),
    (r"\bArdilla\b", "Ardilla"),  # LT confuses Spriggan/squirrel
    (r"\bArdilla\b", "Ardilla"),
    # "you are" confusion
    (r"estás son", "son"),
    (r"tú son", "son"),
    (r"se son", "son"),
    (r"no puede ser", "no puede"),
    # LT does weird capitalization in the middle of sentences
    (
        r"\. [A-Z]",
        lambda m: (
            m.group(0).lower()
            if m.group(0)[1].isupper() and len(m.group(0)) == 2
            else m.group(0)
        ),
    ),
    # Fix: "Pv" -> "PV" (hit points abbreviation)
    (r"\bPv\b", "PV"),
    (r"\bpv\b", "PV"),
    (r"\bPm\b", "PM"),  # Magic points
    (r"\bpm\b", "PM"),
    (r"\bCa\b", "CA"),  # Armour class
    (r"\bca\b", "CA"),
    (r"\bev\b", "EV"),  # Evasion
    (r"\bEv\b", "EV"),
    (r"\bsh\b", "SH"),  # Shield
    (r"\bSh\b", "SH"),
]
